#!/bin/bash

case $1 in
	install)
		wget -qO - http://packages.sil.org/sil.gpg | sudo apt-key add -
		sudo apt-add-repository "deb http://packages.sil.org/ubuntu/ $(lsb_release -sc) main"
		sudo apt-get update
		sudo apt-get install -y ibus-kmfl
		sudo cp -fv ./src/keyboards/*.kmn /usr/share/kmfl
		sudo cp -fv ./src/icons/*.bmp /usr/share/kmfl/icons
		ibus-daemon -rdx
		im-config -n ibus
		;;

	uninstall)
		sudo rm -fv /usr/share/kmfl/*.kmn
		sudo rm -rfv /usr/share/kmfl/icons
		sudo apt-get purge -y ibus-kmfl
		sudo apt-add-repository --remove "deb http://packages.sil.org/ubuntu/ $(lsb_release -sc) main"
		;;
	*)
		echo "Usage: sh ./mmuimc install|uninstall"
		;;
esac
